version: '3.8'

services:
  wol-app:
    # image: ghcr.io/nikolan123/nikowol:latest
    build: .
    container_name: wol-app
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5545
    volumes:
      - ./nikowol_data:/app/data
    restart: unless-stopped
    network_mode: host
